apiVersion: apps/v1
kind:  Deployment
metadata:
  name: fighter-name
  labels:
    app: fighter-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fighter-name
  template:
    metadata:
      labels:
        app: fighter-name
    spec:
      containers:
      - name: service-two
        image: kb674/fighter_two_image:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fighter-name-service
spec:
  selector:
    app: fighter-name
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP    