apiVersion: apps/v1
kind:  Deployment
metadata:
  name: fighter-art
  labels:
    app: fighter-art
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fighter-art
  template:
    metadata:
      labels:
        app: fighter-art
    spec:
      containers:
      - name: service-three
        image: kb674/fighter_three_image:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fighter-art-service
spec:
  selector:
    app: fighter-art
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP    