apiVersion: apps/v1
kind:  Deployment
metadata:
  name: fighter-record
  labels:
    app: fighter-record
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fighter-record
  template:
    metadata:
      labels:
        app: fighter-record
    spec:
      containers:
      - name: service-four
        image: kb674/fighter_four_image:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fighter-record-service
spec:
  selector:
    app: fighter-record
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP    